version: '3.8'
services:

  servernode:
    build:
      context: .
    environment:
      NODE_ENV: develop
    ports:
      - 3000:3000
    command: npm run dev
    develop:
      watch:
        - action: rebuild
          path: .
          target: /usr/src/app/ 
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
      depends_on:
        - mongodb
        - mongo-express

  mongodb:
    container_name: mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME= admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD= password
      - ME_CONFIG_MONGODB_URL= mongodb://admin:password@mongo:27017/
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local